version: '3.8'

services:
  backend:
    build: .
    container_name: exercise_backend
    command: ["python", "-m", "uvicorn", "exercise_api_backend:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "8000:8000"
    depends_on:
      - redis

  worker:
    build: .
    container_name: exercise_worker
    command: ["python", "-m", "celery", "-A", "app.worker.celery_app", "worker", "--loglevel=info"]
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: exercise_redis
    ports:
      - "6379:6379"
