services:
  backend:
    build: .
    container_name: exercise_backend
    command: ["python", "-m", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "8000:8000"
    depends_on:
      - redis
    restart: always

  worker:
    build: .
    container_name: exercise_worker
    command: ["python", "-m", "celery", "-A", "app.worker.celery_app", "worker", "--loglevel=info", "--concurrency=2"]
    depends_on:
      - redis
    restart: always

  redis:
    image: redis:7.2-alpine
    container_name: exercise_redis
    ports:
      - "6379:6379"
    restart: always
